---
- name: Create ZooKeeper group
  group:
    name: "{{ zk_group }}"
    system: True
    state: present

- name: Create ZooKeeper user
  user:
    name: "{{ zk_user }}"
    system: True
    state: present

- name: Create ZooKeeper Directories
  file:
    path: "{{ item }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    recurse: yes
    state: directory
    mode: 0644
  with_items:
    - "{{ zk_config_dir }}"
    - "{{ zk_data_dir }}"
    - "{{ zk_log_dir }}"
    - "{{ zk_install_dir }}"

- name: Download ZooKeeper
  local_action: get_url url="{{ zk_download_url }}" dest="{{ zk_staging_dir }}"
  become: False
  run_once: True

- name: Extract ZooKeeper
  unarchive:
    src: "{{ zk_staging_dir }}/{{ zk_artifact }}"
    dest: "{{ zk_install_dir }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    creates: "{{ zk_real_home }}"
    mode: 0755

- name: Symlink to Current
  file:
    src: "{{ zk_real_home }}"
    dest: "{{ zk_home }}"
    state: link
    force: yes

- name: Copy log4j config
  template:
    src: log4j.properties.j2
    dest: "{{ zk_config_dir }}/log4j.properties"
    owner: root
    group: root
    mode: 644
