- name: Create Exhibitor Directories
  file:
    path: "{{ item }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ exhibitor_install_dir }}"
    - "{{ exhibitor_install_dir }}/{{ exhibitor_version }}"
    
- name: Download Exhibitor jar
  local_action: get_url url="{{ exhibitor_download_url }}" dest="{{ zk_staging_dir }}"
  become: False
  run_once: True

- name: Copy Exhibitor jar
  copy:
    src: "{{ zk_staging_dir }}/{{ exhibitor_artifact }}"
    dest: "{{ exhibitor_install_dir }}/{{ exhibitor_artifact }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_group }}"
    mode: 0755
